### ISSUE TITLE
Release to npmjs on tags (on release created)

### ISSUE THREAD

**Issue by alagane** [linagora/jmap-client-ts#23]
When a commit is tagged, continuous integration should build and push the release to npmjs.

**Comment by jeserkin** [comment]
Is this being done with Travis CI? If so, then `.travis-ci.yml` is missing

**Comment by alagane** [comment]
> Is this being done with Travis CI? If so, then `.travis-ci.yml` is missing

I am trying to do it with GitHub actions.

**Comment by jeserkin** [comment]
Hmm. Not aware of github actions, but sure.

**Comment by alagane** [comment]
First release is here.
https://www.npmjs.com/package/jmap-client-ts
It should work like before, but it fixes a bug with some npm versions not able to build jmap-client-ts dependency correctly if github link was used instead of a deployed version (we had it here https://github.com/linagora/esn-frontend-inbox/issues/533)
