### ISSUE TITLE
Relocate this repository under Linagora org.

### ISSUE THREAD

**Issue by chibenwa** [linagora/jmap-client-ts#44]
What is the impact of moving this repository?

 - [ ] Build tools?
 - [ ] External links?

**Comment by alagane** [comment]
I wonder if the old repository url will be redirected. When renaming GitHub account for example, the ancient username redirects to the new until someone claims it if I remember correctly.

**Comment by alagane** [comment]
Ok, so it seems this is the case:
>All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL.
(from https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)

**Comment by chibenwa** [comment]
> I wonder if the old repository url will be redirected. When renaming GitHub account for example, the ancient username redirects to the new until someone claims it if I remember correctly.

:+1: 

Wow that is a cool feature! I didn't know.

**Comment by alagane** [comment]
Project has been moved.
