### ISSUE TITLE
Specifying properties for  jmapClient.email_get seems to be an issue

### ISSUE THREAD

**Issue by jeserkin** [linagora/jmap-client-ts#56]
Given
```ts
getEmailsWithSpecificProperties(emailIds: string[], properties: ?): Observable<IEmailGetResponse> {
    return from(this.fetchSession())
      .pipe(
        mergeMap(session => from(this.jmapClient.email_get({
          accountId: Object.keys(session.accounts)[0],
          ids: emailIds,
          fetchAllBodyValues: true,
          properties
        })))
      );
  }
```

What would `properties` type be, to accommodate provided method?

Based on the question, it seems to me, that `properties?: (keyof Properties)[];` is not the desired way of specifying type.

**Comment by alagane** [comment]
> What would `properties` type be, to accommodate provided method?

Partial<IEmailGetArguments> maybe?

**Comment by alagane** [comment]
This doesn't work?
`(keyof IEmailProperties)[]`

**Comment by jeserkin** [comment]
As argument type?

**Comment by alagane** [comment]
Instead of the `?` on your first example.

**Comment by jeserkin** [comment]
Okay. Didn't not expect, that it will work. Thanks. That resolved the issue.

**Comment by chibenwa** [comment]
Do we  have code examples that could serve as documentation?

If you did not find it yourself, then others are likely not to find it too...

**Comment by jeserkin** [comment]
I guess only current discussion could serve as documentation for this specific example/problem

**Comment by alagane** [comment]
> Do we have code examples that could serve as documentation?
> 
> If you did not find it yourself, then others are likely not to find it too...

This is more typescript advanced types problems than jmap-client-ts problems.

**Comment by jeserkin** [comment]
Also true, but still would be a nice to have examples. Entirely possible, that my use case came up because of lack of knowledge about certain TypeScript aspect.
