### ISSUE TITLE
upgrade test container & more overridenUrl settings?

### ISSUE THREAD

**Issue by qyb** [linagora/jmap-client-ts#64]
First, James 3.7.0 have implemented Thread/Get (JAMES-3516). It's an important feature and I'd like to push my patch that had been working well with cyrus-imapd.

Second, current constructor has an optional `overriddenApiUrl` argument. I thought we need it when the real James server serves behind a proxy with rewritten path/port (or our test container's port mapping ). But `apiUrl` wasn't the only URL in jmap session response. `downloadUrl`, `uploadUrl`, `eventSourceUrl`, ... all need to be replaced in this scenario. Should we use **overriddenUrl**-object instead of it?

**Comment by qyb** [comment]
Now I get the answers.

> First, James 3.7.0 have implemented Thread/Get (JAMES-3516). It's an important feature and I'd like to push my patch that had been working well with cyrus-imapd.

linagora/tmail-backend:memory-0.5.0 is the first 3.8.0-SNAPSHOT image of tmail-backend, and 0.4.3 is the last 3.7.0-SNAPSHOT image. I'll use 0.5.0 as my test container.

> 
> Second, current constructor has an optional `overriddenApiUrl` argument. I thought we need it when the real James server serves behind a proxy with rewritten path/port (or our test container's port mapping ). But `apiUrl` wasn't the only URL in jmap session response. `downloadUrl`, `uploadUrl`, `eventSourceUrl`, ... all need to be replaced in this scenario. Should we use **overriddenUrl**-object instead of it?

If set `dynamic.jmap.prefix.resolution.enabled=true` in jmap.properties. Then we could use X-JMAP-PREFIX header to get usable URLs in session request.

So we just need one `prefixUrl` argument instead of `overriddenApiUrl` .

**Comment by chibenwa** [comment]
> linagora/tmail-backend:memory-0.5.0 is the first 3.8.0-SNAPSHOT image of tmail-backend, and 0.4.3 is the last 3.7.0-SNAPSHOT image. I'll use 0.5.0 as my test container.

Why not use apache James 3.7.0 ? https://hub.docker.com/layers/james/apache/james/memory-3.7.0/images/sha256-944c7067ec87b262b0ccb8a50204a61058ed6f2033e9dff9323db930cba2618a?context=explore

>> Second, current constructor has an optional overriddenApiUrl argument. I thought we need it when the real James server serves behind a proxy with rewritten path/port (or our test container's port mapping ). But apiUrl wasn't the only URL in jmap session response. downloadUrl, uploadUrl, eventSourceUrl, ... all need to be replaced in this scenario. Should we use overriddenUrl-object instead of it?

> If set dynamic.jmap.prefix.resolution.enabled=true in jmap.properties. Then we could use X-JMAP-PREFIX header to get usable URLs in session request.
> 
> So we just need one prefixUrl argument instead of overriddenApiUrl .

`X-JMAP-PREFIX` was intended to be used by an API gateway.

The use case was exposing two APIs, one legacy using basic auth + a custom JWT mechanism while still having another set of API using OIDC, all of that collocated on the same james deployment: The API gateway then just injects the right values to populate the JMAP session. In short: a deployment detail.

To be fair, as a client you should not care. You should blidly take the endpoints advertized in the JMAP session provided by your backend and just use that. (any thing different would harm inter-operability)

**Comment by chibenwa** [comment]
(so I would rather see less overrides rather than more!

**Comment by chibenwa** [comment]
Ok so that option is IMO harmful and should be dropped.

**Comment by alagane** [comment]
> 

https://github.com/linagora/jmap-client-ts/issues/66
